### ISSUE TITLE
Can you provide some sample streams

### ISSUE THREAD

**Issue by itsholton** [JamesPoole/podcast-skill#1]
Hey,
  I have it installed and am trying to get it to play Daily Tech News show, but it just keeps saying "I didn't get that" or "say the podcast again"  I am not sure it is my config or the stream I am trying.  A sample stream you know works would be great!
Thanks!

**Comment by nerdenator** [comment]
Seconded; I'm trying to debug this on picroft (which I know hasn't been tested) and it'd be nice to have a stream that is known to work on other platforms.

**Comment by JamesPoole** [comment]
Thanks for the feedback guys, Im working now to remove these bugs.

A few small changes have been made so if ye want to download the latest version of the skill using the github link instead of the version in the repo ye can see if it works better for you. There are still a few changes to come.

Something I noticed when testing "Daily Tech News Show" was that I was being redirected to the news skill but it worked fine if I set the Trigger Name to "Daily Tech Show".

And in terms of the streams I use, Linux Unplugged, Art of Manliness and Daily Tech News Show (with above tweak) defo work.

**Comment by JamesPoole** [comment]
I am also looking into new podcast RSS parsers to try and improve RSS compatibility.

**Comment by itsholton** [comment]
JamesPoole,
  I really like where this is going, but I still cannot get this to play on my desktop.  I recently installed the foxnews skill and removed the npr skill as npr was grabbing everything "news."  The Foxnews skill worked immediately, so I began to look at the differences.  I'm no Python programmer, but I did notice some differences in the way actions were called.  Maybe there is something there that will help.

For the record, I am using the following URL for Daily Tech Show:
http://feeds.feedburner.com/DailyTechNewsShow

Is that what you used to get yours to work?  Any suggestions for other places to look?  I did just delete /opt/mycroft/skills/podcast-skill and re-clone it.  Is that the best method?

Many Thanks!

**Comment by JamesPoole** [comment]
Sorry that it is giving you hassle, I'm still working on it and will look into this again.

That URL is fine and I had it working a few days ago so I wonder what is up.

I have found that if you download the skill using msm you should get the most up to date version so you don't actually have to clone the repo directly!

Thanks for the feedback though and I will be back to you shortly! :)

**Comment by LinusSkucas** [comment]
Do you know if urls such as [https://www.npr.org/rss/podcast.php?id=344098539](https://www.npr.org/rss/podcast.php?id=344098539) would work?
I can’t seem to get it working.

**Comment by itsholton** [comment]
@JamesPoole 
Found that my issues with running were resolved after I removed npr-news skill AND UPDATED THE mycroft-core.   It was at 0.9..something and current is 18.2.0. 
 
Here's what I did:
I went into my local mycroft-core folder and ran git pull
    `~/mycroft-core$ git pull`

 then went into msm and ran an update.
  `~/mycroft-core/msm$ ./msm update`

Hope this helps others...
Thanks for the hard work on this!!

**Comment by JamesPoole** [comment]
@itsholton @LinusS1 
I have changed the feed parsing system to something that I think is far more robust to a wider range of RSS feeds. With regards to your questions I have tried both the NPR podcast linked above and the Daily Tech News Show on my desktop mycroft install and they boh work well.

Let me know if things are working as well on your installs.

Thanks for the patience and feedback.

**Comment by JamesPoole** [comment]
@itsholton @LinusS1  @Nerdenator 
Hi Guys,

I found a bug that prevents Mycroft from updating the skill automatically.
This is now fixed.
To get on to the latest version ye will need to remove the skill and reinstall. From there it should stay on the latest version into the future.

If ye could give some feedback on if it is working for ye that would be great!

**Comment by LinusSkucas** [comment]
@JamesPoole 
Hello,
The new phrasing system is working great! It recognized the npr podcast url. However, I ran into some troubles. First, in the skills section where you choose the podcast, I noticed that you can’t  capitalize any letters in the name. If you do, picroft won’t be able to figure the podcast name out. This is a problem because picroft returns the utterance all lowercase.

Next, on picroft, here is my interaction:

```
Me: play the podcast wait wait don’t tell me
Picroft: the episode on deck is: Austin Goolsbee, would you like to play this episode or view the previous episode?
Me:play
Picroft: playing podcast.
<Nothing plays>
```
Something isn’t right here. I haven’t gone digging around looking for errors. I just forked your repo - I’ve got some ideas about improving this 🙂

**Comment by JamesPoole** [comment]
@LinusS1 
I put in some fixes a while ago to fix the capitalisation errors but there might be a bug or two still there if it is still happening for you.

When I test the skill on my desktop, all feeds that I throw at it seem to work perfectly.
However, when I test on my Mark 1, I get your example of "nothing plays" for a lot of URLs. It is quite frustrating and I haven't been able to figure it out yet.

Thanks a mill for having a look yourself! Best of luck with it!

**Comment by itsholton** [comment]
Sorry for the re-post it was not intentional.  I will check out your new mods.
Thanks

**Comment by LinusSkucas** [comment]
@JamesPoole 
What urls would worked on the mark 1?

**Comment by JamesPoole** [comment]
Linux Unplugged is the one that I have as a working example

http://feeds.feedburner.com/linuxunplugged

**Comment by LinusSkucas** [comment]
The Linux Unplugged worked on Picroft

**Comment by itsholton** [comment]
@JamesPoole - The capitalization still seems to be the issue for me.  I am using a linux desktop version on Ubuntu.  As long as I make all my podcast titles lowercase, it is good and works.  If you have no more sample RSS feeds to add to this issue, I would consider it closed.
Otherwise you can add those sample entries here and then consider closing the issue. 
Thanks for all your work on this!
