### ISSUE TITLE
Multiple Podcast settings in Mycroft Home

### ISSUE THREAD

**Issue by itsholton** [JamesPoole/podcast-skill#5]
Note sure what the cause, but there are multiple settings for the Podcast Skill in home.  I believe this is caused by one or the other of these, but not sure:
- Installing on multiple devices
- Removing and reinstalling on the same device different versions of the skill

If from multiple devices, consider adding the device name from settings to the Podcast settings section title.  If some other reason I don't think I can help...  It might be helpful to have different settings on each device or some may think it needs to be the same on every device.
Thanks!!

**Comment by LinusSkucas** [comment]
This seems to me that it is a mycroft home issue. There are little x's on each settings card to get rid of the settings but I don't know what those are for.

**Comment by JamesPoole** [comment]
So I think that is a bug with Mycroft Home and that it is caused if you have multiple mycroft installs with different versions.

If you keep all your installs to the same version, it should just display one settings panel and then all the mycroft installs should pull from the same podcast skill settings

**Comment by itsholton** [comment]
Ok,
  So based on yall's advice, I deleted the settings on Mycroft Home and then removed and reinstalled the version on my Mycroft using the msm method.  THEN I removed any capital letters on my podcast titles (or keywords) at Mycroft Home and now it works.
Thanks!!
